ARG JITSI_IMAGE_REPO=docker.io/jitsi
ARG JITSI_IMAGE_VERSION=stable-10978
FROM ${JITSI_IMAGE_REPO}/web:${JITSI_IMAGE_VERSION}

USER root

COPY index.html base.html body.html head.html title.html plugin.head.html fonts.html /usr/share/jitsi-meet/
COPY app.js conference.js custom.js giphy-analytics-stub.js pwa-worker.js manifest.json /usr/share/jitsi-meet/
COPY libs/ /usr/share/jitsi-meet/libs/
COPY css/all.css /usr/share/jitsi-meet/css/all.css
COPY static/ /usr/share/jitsi-meet/static/
COPY sounds/ /usr/share/jitsi-meet/sounds/
COPY images/ /usr/share/jitsi-meet/images/
COPY lang/ /usr/share/jitsi-meet/lang/
COPY docker/jitsi-core/web/rootfs/defaults/default /defaults/default
COPY docker/jitsi-core/web/rootfs/defaults/meet.conf /defaults/meet.conf
COPY docker/jitsi-core/web/rootfs/defaults/cinema-config.js /defaults/cinema-config.js
COPY interface_config.js /defaults/interface_config.js
